name: CI CD

on:
  push:
    branches:
      - develop
      - feat/cicd
  pull_request:
    branches:
      - develop
      - feat/cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create application-secret.yml
        env:
          APPLICATION_SECRET: ${{secrets.APPLICATION_SECRET}}
        run: echo $APPLICATION_SECRET > src/main/resources/application-secret.yml

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/cicd .
          docker push $DOCKER_USERNAME/cicd

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.EC2_HOST}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/"

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -f